export interface CountryOption {
  code: string;
  name: string;
  label: string;
}

export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: "AF", name: "Afghanistan", label: "Afghanistan (AF)" },
  { code: "AL", name: "Albania", label: "Albania (AL)" },
  { code: "DZ", name: "Algeria", label: "Algeria (DZ)" },
  { code: "AS", name: "American Samoa", label: "American Samoa (AS)" },
  { code: "AD", name: "Andorra", label: "Andorra (AD)" },
  { code: "AO", name: "Angola", label: "Angola (AO)" },
  { code: "AI", name: "Anguilla", label: "Anguilla (AI)" },
  { code: "AQ", name: "Antarctica", label: "Antarctica (AQ)" },
  { code: "AG", name: "Antigua and Barbuda", label: "Antigua and Barbuda (AG)" },
  { code: "AR", name: "Argentina", label: "Argentina (AR)" },
  { code: "AM", name: "Armenia", label: "Armenia (AM)" },
  { code: "AW", name: "Aruba", label: "Aruba (AW)" },
  { code: "AU", name: "Australia", label: "Australia (AU)" },
  { code: "AT", name: "Austria", label: "Austria (AT)" },
  { code: "AZ", name: "Azerbaijan", label: "Azerbaijan (AZ)" },
  { code: "BS", name: "Bahamas", label: "Bahamas (BS)" },
  { code: "BH", name: "Bahrain", label: "Bahrain (BH)" },
  { code: "BD", name: "Bangladesh", label: "Bangladesh (BD)" },
  { code: "BB", name: "Barbados", label: "Barbados (BB)" },
  { code: "BY", name: "Belarus", label: "Belarus (BY)" },
  { code: "BE", name: "Belgium", label: "Belgium (BE)" },
  { code: "BZ", name: "Belize", label: "Belize (BZ)" },
  { code: "BJ", name: "Benin", label: "Benin (BJ)" },
  { code: "BM", name: "Bermuda", label: "Bermuda (BM)" },
  { code: "BT", name: "Bhutan", label: "Bhutan (BT)" },
  { code: "BO", name: "Bolivia", label: "Bolivia (BO)" },
  { code: "BA", name: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina (BA)" },
  { code: "BW", name: "Botswana", label: "Botswana (BW)" },
  { code: "BV", name: "Bouvet Island", label: "Bouvet Island (BV)" },
  { code: "BR", name: "Brazil", label: "Brazil (BR)" },
  { code: "IO", name: "British Indian Ocean Territory", label: "British Indian Ocean Territory (IO)" },
  { code: "BN", name: "Brunei", label: "Brunei (BN)" },
  { code: "BG", name: "Bulgaria", label: "Bulgaria (BG)" },
  { code: "BF", name: "Burkina Faso", label: "Burkina Faso (BF)" },
  { code: "BI", name: "Burundi", label: "Burundi (BI)" },
  { code: "CV", name: "Cabo Verde", label: "Cabo Verde (CV)" },
  { code: "KH", name: "Cambodia", label: "Cambodia (KH)" },
  { code: "CM", name: "Cameroon", label: "Cameroon (CM)" },
  { code: "CA", name: "Canada", label: "Canada (CA)" },
  { code: "KY", name: "Cayman Islands", label: "Cayman Islands (KY)" },
  { code: "CF", name: "Central African Republic", label: "Central African Republic (CF)" },
  { code: "TD", name: "Chad", label: "Chad (TD)" },
  { code: "CL", name: "Chile", label: "Chile (CL)" },
  { code: "CN", name: "China", label: "China (CN)" },
  { code: "CX", name: "Christmas Island", label: "Christmas Island (CX)" },
  { code: "CC", name: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands (CC)" },
  { code: "CO", name: "Colombia", label: "Colombia (CO)" },
  { code: "KM", name: "Comoros", label: "Comoros (KM)" },
  { code: "CG", name: "Congo", label: "Congo (CG)" },
  { code: "CD", name: "Congo (Democratic Republic)", label: "Congo (Democratic Republic) (CD)" },
  { code: "CK", name: "Cook Islands", label: "Cook Islands (CK)" },
  { code: "CR", name: "Costa Rica", label: "Costa Rica (CR)" },
  { code: "HR", name: "Croatia", label: "Croatia (HR)" },
  { code: "CU", name: "Cuba", label: "Cuba (CU)" },
  { code: "CW", name: "Curacao", label: "Curacao (CW)" },
  { code: "CY", name: "Cyprus", label: "Cyprus (CY)" },
  { code: "CZ", name: "Czechia", label: "Czechia (CZ)" },
  { code: "CI", name: "Cote d'Ivoire", label: "Cote d'Ivoire (CI)" },
  { code: "DK", name: "Denmark", label: "Denmark (DK)" },
  { code: "DJ", name: "Djibouti", label: "Djibouti (DJ)" },
  { code: "DM", name: "Dominica", label: "Dominica (DM)" },
  { code: "DO", name: "Dominican Republic", label: "Dominican Republic (DO)" },
  { code: "EC", name: "Ecuador", label: "Ecuador (EC)" },
  { code: "EG", name: "Egypt", label: "Egypt (EG)" },
  { code: "SV", name: "El Salvador", label: "El Salvador (SV)" },
  { code: "GQ", name: "Equatorial Guinea", label: "Equatorial Guinea (GQ)" },
  { code: "ER", name: "Eritrea", label: "Eritrea (ER)" },
  { code: "EE", name: "Estonia", label: "Estonia (EE)" },
  { code: "SZ", name: "Eswatini", label: "Eswatini (SZ)" },
  { code: "ET", name: "Ethiopia", label: "Ethiopia (ET)" },
  { code: "FK", name: "Falkland Islands", label: "Falkland Islands (FK)" },
  { code: "FO", name: "Faroe Islands", label: "Faroe Islands (FO)" },
  { code: "FJ", name: "Fiji", label: "Fiji (FJ)" },
  { code: "FI", name: "Finland", label: "Finland (FI)" },
  { code: "FR", name: "France", label: "France (FR)" },
  { code: "GF", name: "French Guiana", label: "French Guiana (GF)" },
  { code: "PF", name: "French Polynesia", label: "French Polynesia (PF)" },
  { code: "TF", name: "French Southern Territories", label: "French Southern Territories (TF)" },
  { code: "GA", name: "Gabon", label: "Gabon (GA)" },
  { code: "GM", name: "Gambia", label: "Gambia (GM)" },
  { code: "GE", name: "Georgia", label: "Georgia (GE)" },
  { code: "DE", name: "Germany", label: "Germany (DE)" },
  { code: "GH", name: "Ghana", label: "Ghana (GH)" },
  { code: "GI", name: "Gibraltar", label: "Gibraltar (GI)" },
  { code: "GR", name: "Greece", label: "Greece (GR)" },
  { code: "GL", name: "Greenland", label: "Greenland (GL)" },
  { code: "GD", name: "Grenada", label: "Grenada (GD)" },
  { code: "GP", name: "Guadeloupe", label: "Guadeloupe (GP)" },
  { code: "GU", name: "Guam", label: "Guam (GU)" },
  { code: "GT", name: "Guatemala", label: "Guatemala (GT)" },
  { code: "GG", name: "Guernsey", label: "Guernsey (GG)" },
  { code: "GN", name: "Guinea", label: "Guinea (GN)" },
  { code: "GW", name: "Guinea-Bissau", label: "Guinea-Bissau (GW)" },
  { code: "GY", name: "Guyana", label: "Guyana (GY)" },
  { code: "HT", name: "Haiti", label: "Haiti (HT)" },
  { code: "HM", name: "Heard Island and McDonald Islands", label: "Heard Island and McDonald Islands (HM)" },
  { code: "VA", name: "Holy See", label: "Holy See (VA)" },
  { code: "HN", name: "Honduras", label: "Honduras (HN)" },
  { code: "HK", name: "Hong Kong", label: "Hong Kong (HK)" },
  { code: "HU", name: "Hungary", label: "Hungary (HU)" },
  { code: "IS", name: "Iceland", label: "Iceland (IS)" },
  { code: "IN", name: "India", label: "India (IN)" },
  { code: "ID", name: "Indonesia", label: "Indonesia (ID)" },
  { code: "IR", name: "Iran", label: "Iran (IR)" },
  { code: "IQ", name: "Iraq", label: "Iraq (IQ)" },
  { code: "IE", name: "Ireland", label: "Ireland (IE)" },
  { code: "IM", name: "Isle of Man", label: "Isle of Man (IM)" },
  { code: "IL", name: "Israel", label: "Israel (IL)" },
  { code: "IT", name: "Italy", label: "Italy (IT)" },
  { code: "JM", name: "Jamaica", label: "Jamaica (JM)" },
  { code: "JP", name: "Japan", label: "Japan (JP)" },
  { code: "JE", name: "Jersey", label: "Jersey (JE)" },
  { code: "JO", name: "Jordan", label: "Jordan (JO)" },
  { code: "KZ", name: "Kazakhstan", label: "Kazakhstan (KZ)" },
  { code: "KE", name: "Kenya", label: "Kenya (KE)" },
  { code: "KI", name: "Kiribati", label: "Kiribati (KI)" },
  { code: "KP", name: "Korea (North)", label: "Korea (North) (KP)" },
  { code: "KR", name: "Korea (South)", label: "Korea (South) (KR)" },
  { code: "KW", name: "Kuwait", label: "Kuwait (KW)" },
  { code: "KG", name: "Kyrgyzstan", label: "Kyrgyzstan (KG)" },
  { code: "LA", name: "Laos", label: "Laos (LA)" },
  { code: "LV", name: "Latvia", label: "Latvia (LV)" },
  { code: "LB", name: "Lebanon", label: "Lebanon (LB)" },
  { code: "LS", name: "Lesotho", label: "Lesotho (LS)" },
  { code: "LR", name: "Liberia", label: "Liberia (LR)" },
  { code: "LY", name: "Libya", label: "Libya (LY)" },
  { code: "LI", name: "Liechtenstein", label: "Liechtenstein (LI)" },
  { code: "LT", name: "Lithuania", label: "Lithuania (LT)" },
  { code: "LU", name: "Luxembourg", label: "Luxembourg (LU)" },
  { code: "MO", name: "Macao", label: "Macao (MO)" },
  { code: "MG", name: "Madagascar", label: "Madagascar (MG)" },
  { code: "MW", name: "Malawi", label: "Malawi (MW)" },
  { code: "MY", name: "Malaysia", label: "Malaysia (MY)" },
  { code: "MV", name: "Maldives", label: "Maldives (MV)" },
  { code: "ML", name: "Mali", label: "Mali (ML)" },
  { code: "MT", name: "Malta", label: "Malta (MT)" },
  { code: "MH", name: "Marshall Islands", label: "Marshall Islands (MH)" },
  { code: "MQ", name: "Martinique", label: "Martinique (MQ)" },
  { code: "MR", name: "Mauritania", label: "Mauritania (MR)" },
  { code: "MU", name: "Mauritius", label: "Mauritius (MU)" },
  { code: "YT", name: "Mayotte", label: "Mayotte (YT)" },
  { code: "MX", name: "Mexico", label: "Mexico (MX)" },
  { code: "FM", name: "Micronesia", label: "Micronesia (FM)" },
  { code: "MD", name: "Moldova", label: "Moldova (MD)" },
  { code: "MC", name: "Monaco", label: "Monaco (MC)" },
  { code: "MN", name: "Mongolia", label: "Mongolia (MN)" },
  { code: "ME", name: "Montenegro", label: "Montenegro (ME)" },
  { code: "MS", name: "Montserrat", label: "Montserrat (MS)" },
  { code: "MA", name: "Morocco", label: "Morocco (MA)" },
  { code: "MZ", name: "Mozambique", label: "Mozambique (MZ)" },
  { code: "MM", name: "Myanmar", label: "Myanmar (MM)" },
  { code: "NA", name: "Namibia", label: "Namibia (NA)" },
  { code: "NR", name: "Nauru", label: "Nauru (NR)" },
  { code: "NP", name: "Nepal", label: "Nepal (NP)" },
  { code: "NL", name: "Netherlands", label: "Netherlands (NL)" },
  { code: "NC", name: "New Caledonia", label: "New Caledonia (NC)" },
  { code: "NZ", name: "New Zealand", label: "New Zealand (NZ)" },
  { code: "NI", name: "Nicaragua", label: "Nicaragua (NI)" },
  { code: "NE", name: "Niger", label: "Niger (NE)" },
  { code: "NG", name: "Nigeria", label: "Nigeria (NG)" },
  { code: "NU", name: "Niue", label: "Niue (NU)" },
  { code: "NF", name: "Norfolk Island", label: "Norfolk Island (NF)" },
  { code: "MK", name: "North Macedonia", label: "North Macedonia (MK)" },
  { code: "MP", name: "Northern Mariana Islands", label: "Northern Mariana Islands (MP)" },
  { code: "NO", name: "Norway", label: "Norway (NO)" },
  { code: "OM", name: "Oman", label: "Oman (OM)" },
  { code: "PK", name: "Pakistan", label: "Pakistan (PK)" },
  { code: "PW", name: "Palau", label: "Palau (PW)" },
  { code: "PS", name: "Palestine", label: "Palestine (PS)" },
  { code: "PA", name: "Panama", label: "Panama (PA)" },
  { code: "PG", name: "Papua New Guinea", label: "Papua New Guinea (PG)" },
  { code: "PY", name: "Paraguay", label: "Paraguay (PY)" },
  { code: "PE", name: "Peru", label: "Peru (PE)" },
  { code: "PH", name: "Philippines", label: "Philippines (PH)" },
  { code: "PN", name: "Pitcairn", label: "Pitcairn (PN)" },
  { code: "PL", name: "Poland", label: "Poland (PL)" },
  { code: "PT", name: "Portugal", label: "Portugal (PT)" },
  { code: "PR", name: "Puerto Rico", label: "Puerto Rico (PR)" },
  { code: "QA", name: "Qatar", label: "Qatar (QA)" },
  { code: "RO", name: "Romania", label: "Romania (RO)" },
  { code: "RU", name: "Russia", label: "Russia (RU)" },
  { code: "RW", name: "Rwanda", label: "Rwanda (RW)" },
  { code: "RE", name: "Reunion", label: "Reunion (RE)" },
  { code: "BL", name: "Saint Barthelemy", label: "Saint Barthelemy (BL)" },
  { code: "SH", name: "Saint Helena", label: "Saint Helena (SH)" },
  { code: "KN", name: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis (KN)" },
  { code: "LC", name: "Saint Lucia", label: "Saint Lucia (LC)" },
  { code: "MF", name: "Saint Martin", label: "Saint Martin (MF)" },
  { code: "PM", name: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon (PM)" },
  { code: "VC", name: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines (VC)" },
  { code: "WS", name: "Samoa", label: "Samoa (WS)" },
  { code: "SM", name: "San Marino", label: "San Marino (SM)" },
  { code: "ST", name: "Sao Tome and Principe", label: "Sao Tome and Principe (ST)" },
  { code: "SA", name: "Saudi Arabia", label: "Saudi Arabia (SA)" },
  { code: "SN", name: "Senegal", label: "Senegal (SN)" },
  { code: "RS", name: "Serbia", label: "Serbia (RS)" },
  { code: "SC", name: "Seychelles", label: "Seychelles (SC)" },
  { code: "SL", name: "Sierra Leone", label: "Sierra Leone (SL)" },
  { code: "SG", name: "Singapore", label: "Singapore (SG)" },
  { code: "SX", name: "Sint Maarten", label: "Sint Maarten (SX)" },
  { code: "SK", name: "Slovakia", label: "Slovakia (SK)" },
  { code: "SI", name: "Slovenia", label: "Slovenia (SI)" },
  { code: "SB", name: "Solomon Islands", label: "Solomon Islands (SB)" },
  { code: "SO", name: "Somalia", label: "Somalia (SO)" },
  { code: "ZA", name: "South Africa", label: "South Africa (ZA)" },
  { code: "GS", name: "South Georgia", label: "South Georgia (GS)" },
  { code: "SS", name: "South Sudan", label: "South Sudan (SS)" },
  { code: "ES", name: "Spain", label: "Spain (ES)" },
  { code: "LK", name: "Sri Lanka", label: "Sri Lanka (LK)" },
  { code: "SD", name: "Sudan", label: "Sudan (SD)" },
  { code: "SR", name: "Suriname", label: "Suriname (SR)" },
  { code: "SJ", name: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen (SJ)" },
  { code: "SE", name: "Sweden", label: "Sweden (SE)" },
  { code: "CH", name: "Switzerland", label: "Switzerland (CH)" },
  { code: "SY", name: "Syria", label: "Syria (SY)" },
  { code: "TW", name: "Taiwan", label: "Taiwan (TW)" },
  { code: "TJ", name: "Tajikistan", label: "Tajikistan (TJ)" },
  { code: "TZ", name: "Tanzania", label: "Tanzania (TZ)" },
  { code: "TH", name: "Thailand", label: "Thailand (TH)" },
  { code: "TL", name: "Timor-Leste", label: "Timor-Leste (TL)" },
  { code: "TG", name: "Togo", label: "Togo (TG)" },
  { code: "TK", name: "Tokelau", label: "Tokelau (TK)" },
  { code: "TO", name: "Tonga", label: "Tonga (TO)" },
  { code: "TT", name: "Trinidad and Tobago", label: "Trinidad and Tobago (TT)" },
  { code: "TN", name: "Tunisia", label: "Tunisia (TN)" },
  { code: "TR", name: "Turkey", label: "Turkey (TR)" },
  { code: "TM", name: "Turkmenistan", label: "Turkmenistan (TM)" },
  { code: "TC", name: "Turks and Caicos Islands", label: "Turks and Caicos Islands (TC)" },
  { code: "TV", name: "Tuvalu", label: "Tuvalu (TV)" },
  { code: "UG", name: "Uganda", label: "Uganda (UG)" },
  { code: "UA", name: "Ukraine", label: "Ukraine (UA)" },
  { code: "AE", name: "United Arab Emirates", label: "United Arab Emirates (AE)" },
  { code: "GB", name: "United Kingdom", label: "United Kingdom (GB)" },
  { code: "US", name: "United States", label: "United States (US)" },
  { code: "UM", name: "United States Minor Outlying Islands", label: "United States Minor Outlying Islands (UM)" },
  { code: "UY", name: "Uruguay", label: "Uruguay (UY)" },
  { code: "UZ", name: "Uzbekistan", label: "Uzbekistan (UZ)" },
  { code: "VU", name: "Vanuatu", label: "Vanuatu (VU)" },
  { code: "VE", name: "Venezuela", label: "Venezuela (VE)" },
  { code: "VN", name: "Vietnam", label: "Vietnam (VN)" },
  { code: "VG", name: "Virgin Islands (British)", label: "Virgin Islands (British) (VG)" },
  { code: "VI", name: "Virgin Islands (U.S.)", label: "Virgin Islands (U.S.) (VI)" },
  { code: "WF", name: "Wallis and Futuna", label: "Wallis and Futuna (WF)" },
  { code: "EH", name: "Western Sahara", label: "Western Sahara (EH)" },
  { code: "YE", name: "Yemen", label: "Yemen (YE)" },
  { code: "ZM", name: "Zambia", label: "Zambia (ZM)" },
  { code: "ZW", name: "Zimbabwe", label: "Zimbabwe (ZW)" },
  { code: "AX", name: "Aland Islands", label: "Aland Islands (AX)" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", label: "Bonaire, Sint Eustatius and Saba (BQ)" },
];

const validCountryCodes = new Set(COUNTRY_OPTIONS.map(c => c.code));

export function isValidCountryCode(code: string): boolean {
  return validCountryCodes.has(code.toUpperCase());
}

export function getCountryName(code: string): string | undefined {
  const country = COUNTRY_OPTIONS.find(c => c.code === code.toUpperCase());
  return country?.name;
}

export function validateCountryCodes(codes: string[]): { valid: boolean; invalidCodes: string[] } {
  const invalidCodes = codes.filter((code) => !isValidCountryCode(code));
  return {
    valid: invalidCodes.length === 0,
    invalidCodes,
  };
}
