export interface SupportedLanguage {
  code: string;
  name: string;
  region?: string;
}

export const supportedLanguages: SupportedLanguage[] = [
  { code: "af", name: "Afrikaans", region: "Africa" },
  { code: "sq", name: "Albanian", region: "Europe" },
  { code: "am", name: "Amharic", region: "Africa" },
  { code: "ar", name: "Arabic", region: "Middle East" },
  { code: "hy", name: "Armenian", region: "Europe" },
  { code: "as", name: "Assamese", region: "South Asia" },
  { code: "az", name: "Azerbaijani", region: "Asia" },
  { code: "bn", name: "Bangla", region: "South Asia" },
  { code: "ba", name: "Bashkir", region: "Asia" },
  { code: "eu", name: "Basque", region: "Europe" },
  { code: "bho", name: "Bhojpuri", region: "South Asia" },
  { code: "brx", name: "Bodo", region: "South Asia" },
  { code: "bs", name: "Bosnian", region: "Europe" },
  { code: "bg", name: "Bulgarian", region: "Europe" },
  { code: "yue", name: "Cantonese (Traditional)", region: "East Asia" },
  { code: "ca", name: "Catalan", region: "Europe" },
  { code: "hne", name: "Chhattisgarhi", region: "South Asia" },
  { code: "lzh", name: "Chinese (Literary)", region: "East Asia" },
  { code: "zh-Hans", name: "Chinese (Simplified)", region: "East Asia" },
  { code: "zh-Hant", name: "Chinese (Traditional)", region: "East Asia" },
  { code: "sn", name: "chiShona", region: "Africa" },
  { code: "hr", name: "Croatian", region: "Europe" },
  { code: "cs", name: "Czech", region: "Europe" },
  { code: "da", name: "Danish", region: "Europe" },
  { code: "prs", name: "Dari", region: "Middle East" },
  { code: "dv", name: "Divehi", region: "South Asia" },
  { code: "doi", name: "Dogri", region: "South Asia" },
  { code: "nl", name: "Dutch", region: "Europe" },
  { code: "en", name: "English", region: "Global" },
  { code: "et", name: "Estonian", region: "Europe" },
  { code: "fo", name: "Faroese", region: "Europe" },
  { code: "fj", name: "Fijian", region: "Pacific" },
  { code: "fil", name: "Filipino", region: "Southeast Asia" },
  { code: "fi", name: "Finnish", region: "Europe" },
  { code: "fr", name: "French", region: "Europe" },
  { code: "fr-ca", name: "French (Canada)", region: "Americas" },
  { code: "gl", name: "Galician", region: "Europe" },
  { code: "ka", name: "Georgian", region: "Europe" },
  { code: "de", name: "German", region: "Europe" },
  { code: "el", name: "Greek", region: "Europe" },
  { code: "gu", name: "Gujarati", region: "South Asia" },
  { code: "ht", name: "Haitian Creole", region: "Americas" },
  { code: "ha", name: "Hausa", region: "Africa" },
  { code: "he", name: "Hebrew", region: "Middle East" },
  { code: "hi", name: "Hindi", region: "South Asia" },
  { code: "mww", name: "Hmong Daw", region: "Southeast Asia" },
  { code: "hu", name: "Hungarian", region: "Europe" },
  { code: "is", name: "Icelandic", region: "Europe" },
  { code: "ig", name: "Igbo", region: "Africa" },
  { code: "id", name: "Indonesian", region: "Southeast Asia" },
  { code: "ikt", name: "Inuinnaqtun", region: "Americas" },
  { code: "iu", name: "Inuktitut", region: "Americas" },
  { code: "iu-Latn", name: "Inuktitut (Latin)", region: "Americas" },
  { code: "ga", name: "Irish", region: "Europe" },
  { code: "it", name: "Italian", region: "Europe" },
  { code: "ja", name: "Japanese", region: "East Asia" },
  { code: "kn", name: "Kannada", region: "South Asia" },
  { code: "ks", name: "Kashmiri", region: "South Asia" },
  { code: "kk", name: "Kazakh", region: "Asia" },
  { code: "km", name: "Khmer", region: "Southeast Asia" },
  { code: "rw", name: "Kinyarwanda", region: "Africa" },
  { code: "tlh-Latn", name: "Klingon", region: "Fictional" },
  { code: "tlh-Piqd", name: "Klingon (plqaD)", region: "Fictional" },
  { code: "gom", name: "Konkani", region: "South Asia" },
  { code: "ko", name: "Korean", region: "East Asia" },
  { code: "ku", name: "Kurdish (Central)", region: "Middle East" },
  { code: "kmr", name: "Kurdish (Northern)", region: "Middle East" },
  { code: "ky", name: "Kyrgyz", region: "Asia" },
  { code: "lo", name: "Lao", region: "Southeast Asia" },
  { code: "lv", name: "Latvian", region: "Europe" },
  { code: "lt", name: "Lithuanian", region: "Europe" },
  { code: "ln", name: "Lingala", region: "Africa" },
  { code: "dsb", name: "Lower Sorbian", region: "Europe" },
  { code: "lug", name: "Luganda", region: "Africa" },
  { code: "mk", name: "Macedonian", region: "Europe" },
  { code: "mai", name: "Maithili", region: "South Asia" },
  { code: "mg", name: "Malagasy", region: "Africa" },
  { code: "ms", name: "Malay", region: "Southeast Asia" },
  { code: "ml", name: "Malayalam", region: "South Asia" },
  { code: "mt", name: "Maltese", region: "Europe" },
  { code: "mni", name: "Manipuri", region: "South Asia" },
  { code: "mi", name: "Maori", region: "Pacific" },
  { code: "mr", name: "Marathi", region: "South Asia" },
  { code: "mn-Cyrl", name: "Mongolian (Cyrillic)", region: "East Asia" },
  { code: "mn-Mong", name: "Mongolian (Traditional)", region: "East Asia" },
  { code: "my", name: "Myanmar", region: "Southeast Asia" },
  { code: "ne", name: "Nepali", region: "South Asia" },
  { code: "nb", name: "Norwegian", region: "Europe" },
  { code: "nya", name: "Nyanja", region: "Africa" },
  { code: "or", name: "Odia", region: "South Asia" },
  { code: "ps", name: "Pashto", region: "South Asia" },
  { code: "fa", name: "Persian", region: "Middle East" },
  { code: "pl", name: "Polish", region: "Europe" },
  { code: "pt", name: "Portuguese (Brazil)", region: "Americas" },
  { code: "pt-pt", name: "Portuguese (Portugal)", region: "Europe" },
  { code: "pa", name: "Punjabi", region: "South Asia" },
  { code: "otq", name: "Queretaro Otomi", region: "Americas" },
  { code: "ro", name: "Romanian", region: "Europe" },
  { code: "run", name: "Rundi", region: "Africa" },
  { code: "ru", name: "Russian", region: "Europe" },
  { code: "sm", name: "Samoan", region: "Pacific" },
  { code: "sr-Cyrl", name: "Serbian (Cyrillic)", region: "Europe" },
  { code: "sr-Latn", name: "Serbian (Latin)", region: "Europe" },
  { code: "st", name: "Sesotho", region: "Africa" },
  { code: "nso", name: "Sesotho sa Leboa", region: "Africa" },
  { code: "tn", name: "Setswana", region: "Africa" },
  { code: "sd", name: "Sindhi", region: "South Asia" },
  { code: "si", name: "Sinhala", region: "South Asia" },
  { code: "sk", name: "Slovak", region: "Europe" },
  { code: "sl", name: "Slovenian", region: "Europe" },
  { code: "so", name: "Somali", region: "Africa" },
  { code: "es", name: "Spanish", region: "Global" },
  { code: "sw", name: "Swahili", region: "Africa" },
  { code: "sv", name: "Swedish", region: "Europe" },
  { code: "ty", name: "Tahitian", region: "Pacific" },
  { code: "ta", name: "Tamil", region: "South Asia" },
  { code: "tt", name: "Tatar", region: "Europe" },
  { code: "te", name: "Telugu", region: "South Asia" },
  { code: "th", name: "Thai", region: "Southeast Asia" },
  { code: "bo", name: "Tibetan", region: "East Asia" },
  { code: "ti", name: "Tigrinya", region: "Africa" },
  { code: "to", name: "Tongan", region: "Pacific" },
  { code: "tr", name: "Turkish", region: "Europe" },
  { code: "tk", name: "Turkmen", region: "Asia" },
  { code: "uk", name: "Ukrainian", region: "Europe" },
  { code: "hsb", name: "Upper Sorbian", region: "Europe" },
  { code: "ur", name: "Urdu", region: "South Asia" },
  { code: "ug", name: "Uyghur", region: "Asia" },
  { code: "uz", name: "Uzbek", region: "Asia" },
  { code: "vi", name: "Vietnamese", region: "Southeast Asia" },
  { code: "cy", name: "Welsh", region: "Europe" },
  { code: "xh", name: "Xhosa", region: "Africa" },
  { code: "yo", name: "Yoruba", region: "Africa" },
  { code: "yua", name: "Yucatec Maya", region: "Americas" },
  { code: "zu", name: "Zulu", region: "Africa" },
];

export function getLanguageName(code: string): string {
  return supportedLanguages.find(l => l.code === code)?.name || code;
}

export function getLanguageByCode(code: string): SupportedLanguage | undefined {
  return supportedLanguages.find(l => l.code === code);
}
